apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: lqg8f25zl-java-springboot 
  janus-idp.io/tekton: lqg8f25zl-java-springboot
  backstage.io/kubernetes-id: lqg8f25zl-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lqg8f25zl-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml